[tool.poetry]
name = "hangman-attempt-2021"
version = "0.1.0"
description = ""
authors = ["ColeFleming <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
inquirer = "^2.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
